# escape=`
ARG BASE_IMAGE
ARG BUILD_IMAGE

FROM ${BUILD_IMAGE} as build

# TODO: Improve build time by building only the required CSPROJ files

ARG INTERNAL_NUGET_SOURCE
ARG SYSTEM_ACCESSTOKEN

COPY /fitness/server/src /build/src

COPY /fitness/server/nuget.config /fitness/server/Sitecore.Demo.Fitness.sln ./build/
WORKDIR /build

RUN MSBuild /v:minimal /p:Configuration=Debug /p:Platform='Any CPU' /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=false /p:publishUrl=C:\out /p:BuildProjectReferences=true /target:'Clean;Build' /restore "Sitecore.Demo.Fitness.sln"

RUN Copy-Item C:\out\bin\Sitecore.Demo.Fitness.Feature.Automation.dll C:\build\temp\xConnectAutomationServiceRoot\

RUN Copy-Item C:\out\bin\Sitecore.Demo.Fitness.Foundation.Analytics.dll C:\build\temp\xConnectAutomationServiceRoot\

FROM $BASE_IMAGE as production

COPY --from=build /build/temp/xConnectAutomationServiceRoot /worker

# Copy transform files
# NOTE: As we do not use Cake to build, the XDT files are not merged and copied to the transforms folder during build time.
# TODO: Improve the collection of the XDT files.
COPY /fitness/server/src/Feature/Automation/xconnect/App_Data/Config/sitecore/MarketingAutomation/sc.MarketingAutomation.ActivityTypes.xml.xdt /transforms/App_Data/Config/sitecore/MarketingAutomation/
COPY /fitness/server/src/Feature/Automation/xconnect/App_Data/Config/sitecore/MarketingAutomation/sc.MarketingAutomation.ContactLoader.xml.xdt /transforms/App_Data/Config/sitecore/MarketingAutomation/

RUN (Get-ChildItem -Path 'C:\\transforms\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ActivityTypes*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\worker\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ActivityTypes.xml' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };

RUN (Get-ChildItem -Path 'C:\\transforms\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ContactLoader*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\worker\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ContactLoader.xml' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };
