---
ID: "e6cf563e-7e12-43a2-b711-12d2f685e6ce"
Parent: "339b4260-2b3f-49cc-b95b-c0438d3c37dd"
Template: "3505f93a-1bbd-4ea4-bfab-09f44e88a594"
Path: /sitecore/system/Settings/Analytics/Marketing Automation/Activity Types/Send push notification/Paths/Default
DB: master
SharedFields:
- ID: "ec7ee750-6c26-4def-aa5f-71dcd3a875de"
  Hint: Key
  Value: default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "229cea16-4ad6-495a-aa42-0e0e05709162"
      Hint: Name
      Value: Default
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170227T125312Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
