# escape=`
ARG BASE_IMAGE
ARG BUILD_IMAGE

FROM ${BUILD_IMAGE} as build

ARG INTERNAL_NUGET_SOURCE
ARG SYSTEM_ACCESSTOKEN

COPY /fitness/server/src /build/src

COPY /fitness/server/nuget.config /fitness/server/Sitecore.Demo.Fitness.sln ./build/
WORKDIR /build

RUN MSBuild /v:minimal /p:Configuration=Debug /p:Platform='Any CPU' /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=false /p:publishUrl=C:\out /p:BuildProjectReferences=true /target:'Clean;Build' /restore "Sitecore.Demo.Fitness.sln"

FROM $BASE_IMAGE as production

# Clear transforms folder from base image
RUN  Remove-Item -Path C:\inetpub\wwwroot\transforms\* -Recurse

COPY --from=build /out/ /inetpub/wwwroot/

# Copy the fitness app config
COPY /fitness/app/sitecore/config/*.config /inetpub/wwwroot/App_Config/Include/Sitecore.Demo.Fitness/
# Copy the fitness-kiosk app config
COPY /fitness/kiosk/sitecore/config/*.config /inetpub/wwwroot/App_Config/Include/Sitecore.Demo.Fitness/

# Copy transform files
# NOTE: As we do not use Cake to build, the XDT files are not merged and copied to the transforms folder during build time.
# TODO: Improve the collection of the XDT files.
COPY /fitness/server/src/Project/AppItems/code/Web.config.xdt /inetpub/wwwroot/transforms/
COPY /fitness/server/src/Project/AppItems/code/App_Config/Layers.config.xdt /inetpub/wwwroot/transforms/App_Config/

RUN (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\transforms\\web*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\inetpub\\wwwroot\\web.config' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };

RUN (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\transforms\\App_Config\\Layers*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\inetpub\\wwwroot\\App_Config\\layers.config' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };
