version: '2.4'

services:

  sql:
    image: ${REGISTRY}lighthouse-jss-sql:${DEMO_VERSION}-linux
    isolation: default
    build:
      context: .
      dockerfile: ./docker/images/windows/demo-sqldev/Dockerfile.linux
      args:
        BASE_IMAGE: ${REGISTRY}lighthouse-sql:${LIGHTHOUSE_VERSION}-linux
    volumes:
      - .\data\sql:/var/opt/mssql/data
    mem_limit: 2GB
    ports:
      - "44010:1433"
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
      USER_PASSWORD: "b"
      ADMIN_PASSWORD: "b"
      ADMIN_USER_NAME: "sitecore\\superuser"
      DISABLE_DEFAULT_ADMIN: 'FALSE'

  app:
    image: ${REGISTRY}lighthouse-jss-app:${DEMO_VERSION}-linux
    isolation: default
    build:
      context: .
      dockerfile: ./docker/images/linux/demo-app/dockerfile
      args:
        BUILD_IMAGE: node:10.21.0-jessie
        BASE_IMAGE: node:10.21.0-alpine
    ports:
      - "44040:80"
    environment:
      SITECORE_API_HOST: http://app-cd.sitecoredemo.io

  kiosk:
    image: ${REGISTRY}lighthouse-jss-kiosk:${DEMO_VERSION}-linux
    isolation: default
    build:
      context: .
      dockerfile: ./docker/images/linux/demo-kiosk/dockerfile
      args:
        BUILD_IMAGE: node:10.21.0-jessie
        BASE_IMAGE: node:10.21.0-alpine
    ports:
      - "44040:80"
    environment:
      SITECORE_API_HOST: http://kiosk-cd.sitecoredemo.io
