version: '2.4'

services:
  app:
    image: ${REGISTRY}lighthouse-jss-app:${DEMO_VERSION}
    isolation: default
    build:
      context: .
      dockerfile: ./docker/images/linux/demo-app/dockerfile
      args:
        BUILD_IMAGE: node:10.21.0-jessie
        BASE_IMAGE: node:10.21.0-alpine
    ports:
      - "44040:80"
    environment:
      SITECORE_API_HOST: http://app-cd.sitecoredemo.io

  kiosk:
    image: ${REGISTRY}lighthouse-jss-kiosk:${DEMO_VERSION}
    isolation: default
    build:
      context: .
      dockerfile: ./docker/images/linux/demo-kiosk/dockerfile
      args:
        BUILD_IMAGE: node:10.21.0-jessie
        BASE_IMAGE: node:10.21.0-alpine
    ports:
      - "44040:80"
    environment:
      SITECORE_API_HOST: http://kiosk-cd.sitecoredemo.io