version: '2.4'

services:
  dacpac:
    image: dacpac:${DEMO_VERSION}
    isolation: ${ISOLATION}
    build:
      context: .
      dockerfile: ./docker/images/windows/demo-sqldev/Dockerfile.dacpac
      args:
        BUILD_IMAGE: ${REGISTRY}demo-build-sdk:${SITECORE_VERSION}
        INTERNAL_NUGET_SOURCE: ${INTERNAL_NUGET_SOURCE}
        SYSTEM_ACCESSTOKEN: ${SYSTEM_ACCESSTOKEN}