# escape=`
ARG BASE_IMAGE
ARG BUILD_IMAGE

FROM ${BUILD_IMAGE} as build

# TODO: Improve build time by building only the required CSPROJ files

COPY /fitness/server/src /build/src

COPY /fitness/server/nuget.config /fitness/server/Sitecore.Demo.Fitness.sln ./build/
WORKDIR /build

RUN MSBuild /v:minimal /p:Configuration=Debug /p:Platform='Any CPU' /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=false /p:publishUrl=C:\out /p:BuildProjectReferences=true /target:'Clean;Build' /restore "Sitecore.Demo.Fitness.sln"

RUN Copy-Item C:\out\bin\Sitecore.Demo.* C:\build\temp\xConnectRoot\bin
RUN Copy-Item C:\out\App_Data\* C:\build\temp\xConnectRoot\App_Data -Recurse -Verbose

FROM $BASE_IMAGE as production

COPY /docker/images/demo-xconnect /inetpub/wwwroot/App_data/Config/sitecore/CoreServices

COPY --from=build /build/temp/xConnectRoot /inetpub/wwwroot

RUN (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ActivityTypes.*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\inetpub\\wwwroot\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ActivityTypes.xml' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };

RUN (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ContactLoader.*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\inetpub\\wwwroot\\App_Data\\Config\\sitecore\\MarketingAutomation\\sc.MarketingAutomation.ContactLoader.xml' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };
