# escape=`

ARG BASE_IMAGE
ARG BUILD_IMAGE

FROM ${BUILD_IMAGE} as build

# Install latest PackageProvider (required for Sitecore.Courier)
RUN Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force

COPY scripts/Packaging/ /packaging

COPY /fitness/server/src /src

RUN .\packaging\generate-update-package.ps1 -target (Resolve-Path /src) -output /output

FROM $BASE_IMAGE as data

COPY --from=build /output/ /output/

COPY docker/images/demo-sqldev/data/ /output

RUN C:\DeployDatabases.ps1 -ResourcesDirectory "/output/data"; `
    C:\DeployDatabases.ps1 -ResourcesDirectory "/output/descendants"

RUN Remove-Item "/output" -Recurse

FROM data as production

COPY /docker/images/demo-sqldev/sql /sql
