# escape=`

ARG BASE_IMAGE
ARG BUILD_IMAGE

ARG CONTENTHUB_CONNECTOR_ASSETS
ARG HEADLESS_ASSETS
ARG HORIZON_INTEGRATION_ASSETS
ARG SPE_ASSETS
ARG SPS_ASSETS

FROM ${CONTENTHUB_CONNECTOR_ASSETS} as contenthub_connector_assets
FROM ${HEADLESS_ASSETS} as headless_assets
FROM ${HORIZON_INTEGRATION_ASSETS} as horizon_integration_assets
FROM ${SPE_ASSETS} as spe_assets
FROM ${SPS_ASSETS} as sps_assets

FROM ${BASE_IMAGE} as base


COPY --from=contenthub_connector_assets /module/db /module_data/contenthub_connector_assets
COPY --from=headless_assets /module/db /module_data/headless_assets
COPY --from=horizon_integration_assets /module/db /module_data/horizon_integration_assets
COPY --from=spe_assets /module/db /module_data/spe_assets
COPY --from=sps_assets /module/db /module_data/sps_assets

RUN $modules = @('contenthub_connector_assets', 'headless_assets','horizon_integration_assets','spe_assets','sps_assets'); `
    foreach($module in $modules) { C:\DeployDatabases.ps1 -ResourcesDirectory /module_data/$module; Remove-Item -Path /module_data/$module -Recurse -Force; }

FROM ${BUILD_IMAGE} as build

# Install latest PackageProvider (required for Sitecore.Courier)
RUN Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force

COPY scripts/Packaging/ /packaging

COPY /fitness/server/src /src

RUN .\packaging\generate-update-package.ps1 -target (Resolve-Path /src) -output /output

FROM base as data

COPY --from=build /output/ /output/

COPY docker/images/demo-sqldev/data/ /output

RUN C:\DeployDatabases.ps1 -ResourcesDirectory "/output/data"; `
    C:\DeployDatabases.ps1 -ResourcesDirectory "/output/descendants"

RUN Remove-Item "/output" -Recurse

FROM data as production

COPY /docker/images/demo-sqldev/sql /sql

COPY /docker/images/demo-sqldev/HashPassword.ps1 /docker/images/demo-sqldev/start-override.ps1 /

CMD ./start-override -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose