# Keep this dockerfile even if it does nothing useful. It serves to build Omni pull requests images of all Platform containers to easily test omni pull requests using the democli.
ARG BASE_IMAGE

FROM $BASE_IMAGE as production
