ARG BUILD_IMAGE
ARG BASE_IMAGE

FROM $BUILD_IMAGE as build

RUN npm install -g @sitecore-jss/sitecore-jss-cli

WORKDIR /kiosk

# Just the package.json first to improve layer cache
COPY fitness/kiosk/package*.json ./

RUN npm install

COPY fitness/kiosk/ ./

# setup to use static values we'll later replace with env vars
# (for values that are baked into the server bundle)
RUN jss setup --layoutServiceHost %layoutServiceHost% --apiKey 309ec3e9-b911-4a0b-aa8d-425045b6dcbd --nonInteractive

ARG REACT_APP_GOOGLE_API_KEY
ENV REACT_APP_GOOGLE_API_KEY=${REACT_APP_GOOGLE_API_KEY}

RUN npm run build

# Rename all .js files to .js.base (so we can bootstrap tokens later)
RUN find /kiosk/build -name '*.js' | xargs -I % mv % %.base

FROM $BUILD_IMAGE as ssr

WORKDIR /ssr

# Just the package.json first to improve layer cache
COPY fitness/kiosk-node-ssr/package*.json ./

RUN npm install

COPY fitness/kiosk-node-ssr/ ./

COPY scripts/Docker/ ./

FROM $BASE_IMAGE as production

WORKDIR /deploy

COPY --from=ssr /ssr ./

COPY --from=build /kiosk/build ./dist/lighthousefitness-kiosk

RUN ["chmod", "+x", "./bootstrap.sh"]

ENV SITECORE_APP_NAME=lighthousefitness-kiosk
ENV SITECORE_JSS_SERVER_BUNDLE=./dist/${SITECORE_APP_NAME}/server.bundle.js
ENV SITECORE_API_HOST=http://kiosk-cd
ENV SITECORE_API_KEY={EBF6D5C1-EB80-4B15-91AB-DD3845797774}
ENV SITECORE_ENABLE_DEBUG=true
ENV PORT=80

ENTRYPOINT npm run dockerlinux

EXPOSE ${PORT}