version: '2.4'

services:

  sql:
    image: ${REGISTRY}demo/lighthouse-headless-mssql:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    isolation: default
    build:
      context: ../
      dockerfile: ./docker/images/demo-sqldev/Dockerfile.linux
      args:
        BASE_IMAGE: ${REGISTRY}community/sitecore-xm1-custom-spe-headless-mssql:10.1.0-linux
        HORIZON_INTEGRATION_ASSETS: ${REGISTRY}community/modules/custom-horizon-integration-xp1-assets:2.25-linux
        CMP_ASSETS: ${REGISTRY}community/modules/custom-cmp-xp1-assets:4.0.0-linux
    volumes:
      - .\data\sql:/var/opt/mssql/data
    mem_limit: 2GB
    ports:
      - "44010:1433"
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
      USER_PASSWORD: "b"
      ADMIN_PASSWORD: "b"
      ADMIN_USER_NAME: "sitecore\\superuser"
      DISABLE_DEFAULT_ADMIN: 'FALSE'
      EXM_BASE_URL: "https://${CD_HOST}"
      BOOT_OVERRIDE_SCRIPTS: "Demo-Boot-Platform-Linux.ps1"

  init:
    healthcheck:
      test: ["CMD", "powershell", "ps"]
    image: ${REGISTRY}demo/lighthouse-headless-init:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    build:
      context: ./images/demo-init
      dockerfile: Dockerfile.linux
      args:
        BUILD_IMAGE: mcr.microsoft.com/dotnet/sdk:3.1-alpine
        BASE_IMAGE: mcr.microsoft.com/dotnet/runtime:3.1-alpine
    environment:
      ADMIN_PASSWORD: ${SITECORE_ADMIN_PASSWORD}
      ADMIN_USER_NAME: "superuser"
      HOST_CD: "http://cd"
      HOST_CM: "http://cm"
      HOST_PS: "http://ps:5000"
      HOST_ID: "http://id"

  app:
    image: ${REGISTRY}demo/lighthouse-headless-app:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    isolation: default
    build:
      context: ../
      dockerfile: ./docker/images/demo-app/dockerfile.linux
      args:
        BUILD_IMAGE: node:10.21.0-jessie
        BASE_IMAGE: node:10.21.0-alpine
    ports:
      - "44040:80"
    environment:
      SITECORE_API_HOST: http://${APP_CD_HOST}
      PROXY_API_HOST: https://${APP_HOST}
      REACT_APP_FIREBASE_MESSAGING_PUSH_KEY: ${REACT_APP_FIREBASE_MESSAGING_PUSH_KEY}
      REACT_APP_FIREBASE_SENDER_ID: ${REACT_APP_FIREBASE_SENDER_ID}
      REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID}
      REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
      REACT_APP_FIREBASE_APP_ID: ${REACT_APP_FIREBASE_APP_ID}
      REACT_APP_GOOGLE_API_KEY: ${REACT_APP_GOOGLE_API_KEY}
    networks:
      demo:
        aliases:
          - app.${HOSTNAME_SUFFIX}
  kiosk:
    image: ${REGISTRY}demo/lighthouse-headless-kiosk:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    isolation: default
    build:
      context: ../
      dockerfile: ./docker/images/demo-kiosk/dockerfile.linux
      args:
        BUILD_IMAGE: node:10.21.0-jessie
        BASE_IMAGE: node:10.21.0-alpine
    ports:
      - "44041:80"
    environment:
      SITECORE_API_HOST: http://${KIOSK_CD_HOST}
      PROXY_API_HOST: https://${KIOSK_HOST}
      REACT_APP_GOOGLE_API_KEY: ${REACT_APP_GOOGLE_API_KEY}
    networks:
      demo:
        aliases:
          - kiosk.${HOSTNAME_SUFFIX}
  boxever:
    image: ${REGISTRY}demo/lighthouse-boxever-proxy:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    build:
      context: ./images/demo-boxever
networks:
  demo:
    external:
      name: nat
