steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'
    updateAssemblyInfo: true
- task: PowerShell@2
  displayName: 'Set correct image tag'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=tag]$(GitVersion.MajorMinorPatch)"'
  condition: eq(variables['GitVersion.PreReleaseLabel'], '')
- task: PowerShell@2
  displayName: 'Tag the PR without the version number'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=tag]$(GitVersion.PreReleaseLabel)"'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
- task: PowerShell@2
  displayName: 'Set default value for additionalImageTags'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=additionalImageTags]$(GitVersion.PreReleaseLabel)"'
- task: PowerShell@2
  displayName: 'Set :latest tag'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=additionalImageTags]latest"'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
- task: PowerShell@2
  displayName: 'Set :stable tag'
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=additionalImageTags]stable"'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))