# escape=`
ARG BASE_IMAGE
ARG BUILD_IMAGE

ARG TOOLS_ASSETS
ARG CONTENTHUB_CONNECTOR_ASSETS
ARG HEADLESS_ASSETS
ARG SPS_ASSETS

FROM ${TOOLS_ASSETS} as tools_assets
FROM ${CONTENTHUB_CONNECTOR_ASSETS} as contenthub_connector_assets
FROM ${HEADLESS_ASSETS} as headless_assets
FROM ${SPS_ASSETS} as sps_assets

FROM ${BASE_IMAGE} as base

COPY --from=tools_assets /tools/ /tools/

COPY --from=contenthub_connector_assets /module/cm/content /inetpub/wwwroot
COPY --from=headless_assets /module/cm/content /inetpub/wwwroot

FROM ${BUILD_IMAGE} as build

ARG INTERNAL_NUGET_SOURCE
ARG SYSTEM_ACCESSTOKEN

COPY /fitness/server/src /build/src

COPY /fitness/server/nuget.config /fitness/server/Sitecore.Demo.Fitness.sln ./build/
WORKDIR /build

RUN MSBuild /v:minimal /p:Configuration=Debug /p:Platform='Any CPU' /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=false /p:publishUrl=C:\out /p:BuildProjectReferences=true /target:'Clean;Build' /restore "Sitecore.Demo.Fitness.sln"

FROM base as production

COPY --from=build /out/ /inetpub/wwwroot/

COPY /docker/images/demo-cd/data/transforms/ /inetpub/wwwroot/transforms/

# Copy the fitness app config
COPY /fitness/app/sitecore/config/*.config /inetpub/wwwroot/App_Config/Include/Sitecore.Demo.Fitness/
# Copy the fitness-kiosk app config
COPY /fitness/kiosk/sitecore/config/*.config /inetpub/wwwroot/App_Config/Include/Sitecore.Demo.Fitness/

# Copy transform files
# NOTE: As we do not use Cake to build, the XDT files are not merged and copied to the transforms folder during build time.
# TODO: Improve the collection of the XDT files.
COPY /fitness/server/src/Project/AppItems/code/Web.config.xdt /inetpub/wwwroot/transforms/
COPY /fitness/server/src/Project/AppItems/code/App_Config/Layers.config.xdt /inetpub/wwwroot/transforms/App_Config/
COPY /fitness/server/src/Project/AppItems/code/App_Config/ConnectionStrings.config.xdt /inetpub/wwwroot/transforms/App_Config/

RUN (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\transforms\\web*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\inetpub\\wwwroot\\web.config' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };

RUN (Get-ChildItem -Path '/inetpub/wwwroot/transforms/ConnectionStrings*.xdt' -Recurse ) | `
    ForEach-Object { & '/tools/scripts/Invoke-XdtTransform.ps1' -Path '/inetpub/wwwroot/app_config/ConnectionStrings.config' -XdtPath $_.FullName `
    -XdtDllPath '/tools/bin/Microsoft.Web.XmlTransform.dll'; };

RUN (Get-ChildItem -Path 'C:\\inetpub\\wwwroot\\transforms\\App_Config\\Layers*.xdt' -Recurse ) | `
    ForEach-Object { & 'C:\\tools\\scripts\\Invoke-XdtTransform.ps1' -Path 'C:\\inetpub\\wwwroot\\App_Config\\layers.config' -XdtPath $_.FullName `
    -XdtDllPath 'C:\\tools\\bin\\Microsoft.Web.XmlTransform.dll'; };

RUN icacls 'C:\inetpub\wwwroot' /grant 'IIS_IUSRS:(OI)(CI)F' /t | Out-Null