---
ID: "48050e2d-07c6-4c17-b250-2dedd10f0526"
Parent: "170ce687-6234-4f70-b6a8-3dcdd441a048"
Template: "4a6a7e36-2481-438f-a9ba-0453ecc638fa"
Path: /sitecore/system/Marketing Control Panel/Profiles/Age Group/Pattern Cards/default
DB: master
Languages:
- Language: en
  Fields:
  - ID: "fe732790-2ddb-4657-a882-c2fce1fbf0c9"
    Hint: Name
    Value: default
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181109T035507Z
