# escape=`

ARG BASE_IMAGE
ARG BUILD_IMAGE

FROM ${BUILD_IMAGE} as build

# Install latest PackageProvider (required for Sitecore.Courier)
RUN Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force

COPY scripts/Packaging/ /packaging

COPY /fitness/server/src /src

RUN .\packaging\generate-update-package.ps1 -target (Resolve-Path /src) -output /output

FROM $BASE_IMAGE as data

COPY --from=build /output/ /output/

COPY docker/images/windows/demo-sqldev/data/ /output

RUN C:\DeployDatabases.ps1 -ResourcesDirectory "/output/data"; `
    C:\DeployDatabases.ps1 -ResourcesDirectory "/output/descendants"

RUN Remove-Item "/output" -Recurse

FROM data as production

ENV USER_PASSWORD="b"
ENV ADMIN_USER_NAME="sitecore\superuser"
ENV SITECORE_ADMIN_PASSWORD="b"
ENV DISABLE_DEFAULT_ADMIN=FALSE
ENV EXM_BASE_URL=http://cd
ENV SQL_SERVER="mssql"
ENV EXM_KIOSK_CD_BASE_URL=http://kiosk-cd
ENV EXM_APP_BASE_URL=http://app
ENV START_OVERRIDE_SCRIPTS="start-override-platform-windows.ps1;start-override-headless-windows.ps1"

COPY /docker/images/windows/demo-sqldev/sql /sql

COPY /docker/images/windows/demo-sqldev/start-override-headless-windows.ps1 /
