# escape=`
ARG BUILD_IMAGE

FROM $BUILD_IMAGE as build

RUN Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; `
    Install-Module -Name Sitecore.Courier -Repository PSGallery -Force -Confirm:$False  -RequiredVersion 1.4.3; `
    Import-Module Sitecore.Courier -Force -Verbose;

COPY /fitness/server/src /src

RUN New-CourierPackage -Target (Resolve-Path /src) -Output /output -SerializationProvider "Rainbow" -IncludeFiles $false -EnsureRevision $true -DacPac $true -Verbose
