ARG BUILD_IMAGE
ARG BASE_IMAGE

# Build the JSS app
FROM $BUILD_IMAGE as app

WORKDIR /app

# JSS CLI
RUN npm install -g @sitecore-jss/sitecore-jss-cli

# Just the package.json first to improve layer cache
COPY fitness/app/package*.json ./

RUN npm install

COPY fitness/app/ ./

# Note: layoutServiceHost must be https normally
RUN jss setup --layoutServiceHost %layoutServiceHost% --apiKey {EBF6D5C1-EB80-4B15-91AB-DD3845797774} --nonInteractive

RUN jss build




# Build the node-SSR
FROM $BUILD_IMAGE as ssr

WORKDIR /ssr

# Just the package.json first to improve layer cache
COPY fitness/app-node-ssr/package*.json ./

RUN npm install

COPY fitness/app-node-ssr/ ./

COPY scripts/Docker/ ./



FROM $BASE_IMAGE as production

ENV NPM_CONFIG_LOGLEVEL info

COPY --from=app /nodejs /nodejs

USER ContainerAdministrator
RUN setx PATH "%PATH%;C:\nodejs;" /M

WORKDIR /deploy

COPY --from=ssr /ssr ./

COPY --from=app /app/build ./dist/lighthousefitness

ENV SITECORE_APP_NAME=lighthousefitness
ENV SITECORE_JSS_SERVER_BUNDLE=./dist/${SITECORE_APP_NAME}/server.bundle.js
ENV SITECORE_API_HOST=http://app-cd
ENV SITECORE_API_KEY={EBF6D5C1-EB80-4B15-91AB-DD3845797774}
ENV SITECORE_ENABLE_DEBUG=true
ENV PORT=80

EXPOSE ${PORT}

ENTRYPOINT ["C:\\nodejs\\npm.cmd", "run", "docker"]